spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    username: root
    password: 870124zxc
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_metabook
    driver-class-name: com.mysql.cj.jdbc.Driver
